CREATE DATABASE IF NOT EXISTS securechat;
USE securechat;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    pwd_hash VARCHAR(64) NOT NULL,
    salt BLOB NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);